services:
  - type: web
    name: app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "app.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: pop-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: pop-db
    plan: free
