services:
  - type: web
    name: app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-ZXbq1pQ1bZkF9fJ0qT0h8!uSYtGqL7H4V^cM2@k9NwVg#rT2"  # pode deixar generateValue: true, se preferir
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"        # depois do primeiro deploy, troque para o domínio gerado pelo Render (ex: "app-xxxxx.onrender.com")
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: pop-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: pop-db
    plan: free
