services:
  - type: web
    name: app
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn app.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pop-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: pop-db
    plan: free
