# Generated by Django 5.2.5 on 2025-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('su_identifier', models.CharField(blank=True, max_length=120, verbose_name='Identificador da SU')),
                ('user_name', models.CharField(max_length=120, verbose_name='Nome')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensagem de diagnóstico')),
                ('category', models.CharField(choices=[('normal', 'Normal'), ('critica', 'Crítica')], default='normal', max_length=20, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='diagnostics_categor_0243e3_idx'), models.Index(fields=['-created_at'], name='diagnostics_created_3688c9_idx'), models.Index(fields=['title'], name='diagnostics_title_485110_idx')],
            },
        ),
    ]
